[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mis_dro"
authors = [
    {name = "Patrick O'Hara", email = "patrick.h.o-hara@warwick.ac.uk"},
    {name = "Harita Dellaporta", email = "C.Dellaporta@warwick.ac.uk"},
]
description = "Misspecified DRO"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["Distributionally Robust Optimisation", "Bayesian"]
license = {text = "BSD-3-Clause"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "gurobipy>=11.0.0",
    "joblib>=1.3.2",
    "numpy>=1.26.2",
    "pandas>=2.1.4",
    "scikit_learn>=1.3.2",
    "scipy>=1.11.4",
    "tqdm>=4.66.1",
    "typer>=0.9.0",
    "jax>=0.4.23",
    "jaxlib>=0.4.23",
    "pot>=0.9.1"
]
dynamic = ["version"]

[tool.setuptools]
packages = ["bayesian_dro", "mis_dro"]

[project.scripts]
misdro = "mis_dro.main:app"